version: '3'

services:
    react_app:
      environment:
        REACT_APP_SERVER: http://localhost:4700/
      build: 
        context: .
        args:
         REACT_APP_SERVER: http://localhost:4700/
      ports:
        - 5000:80
        